apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: 
    metadata:
      labels: 
        app: auth
    spec:
      containers:
        - name: auth
          image: kkunle/auth
          env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: DB
            valueFrom: 
              secretKeyRef: 
                name: database
                key: DB
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: databasepassword
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000